name: Request

on:
  #push:
  schedule:
  - cron: "* 5 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install poetry
      run: pipx install poetry==1.7.1

    - name: Install python
      uses: actions/setup-python@v5
      with:
          python-version: '3.11'

    - name: Install python dependencies
      run: poetry install
        
    - name: Run Python script
      run: poetry run python main.py
      
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Automated request for EPEX auction results"
        branch: main
